# Generated by Django 5.1.7 on 2025-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('numero_cadastro', models.CharField(max_length=6, unique=True)),
                ('importancia', models.IntegerField(choices=[(1, 'Aluno'), (2, 'Professor'), (3, 'Diretor')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
