# Generated by Django 5.1.7 on 2025-04-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0002_auto_20250401_0136'),
    ]

    operations = [
    ]
