# Generated by Django 5.1.7 on 2025-04-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0003_auto_20250401_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
